### ISSUE TITLE
Multi line footnotes are complicated

### ISSUE THREAD

**Issue by arximboldi** [Kriegslustig/showdown-footnotes#1]
Hi!

I am trying multi line footnotes to work the way I like.  Here is first thing I tried:

```
[^1] This is a footnote that
is split in two lines.
```

This feels like natural manual word wrapping, that normal markdown does nothing special about. but this library is putting the text `This is a footnote that` inside the footnote and `is split in two lines` outside the footnote.

Next thing I tried, as suggested in the readme, is doing something like:

```
[^1] 
    This is a footnote that
    is split in two lines.
```

However, this is the generated HTML:

``` html
<p><small class="footnote" id="footnote-1"><a href="#footnote-1">[1]</a>:</small></p>
<p><small class="footnote" id="footnote-1">This is a footnote that is split in two lines.</small></p>
```

As you can see, the `[1]:` and the bodiy of text are split in two paragraphs, with no common ancestor or class, so it is impossible to style this to avoid the inter-paragraph space between the [1] and the footnote text itself.

My workaround so far is to not do word-wrap in my footnotes, but this is undesirable and does not work with multi-paragraph footnotes.

Thanks!

JP

**Comment by halbgut** [comment]
Thanks for the detailed report. I'll look into it.

**Comment by halbgut** [comment]
The bug is fixed in version 2.0.0, so I'm removing the bug label. In the new version I differentiate between multi and single line footnotes. The former are wrapped inside a `<small>` and the latter in a `<div>`. I'm planning to implement your first example. But it would be as a single line footnote.

```
[^1]: This is a
single line footnote

    This is an unrelated codeblock
```

**Comment by arximboldi** [comment]
Make sense, thanks!

**Comment by halbgut** [comment]
Single line footnotes now (>= 2.1.0) work as described above.
